name: callz

on:
  workflow_call:
    inputs:
      accountbundle:
        required: true
        type: string

jobs:
  called:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        regions: ["us-east-2"]

    steps:

      - name: Print OS
        run: |
          echo ${{ matrix.region }}
          echo ${{ inputs.accountbundle }} | fold -w12
        shell: bash

