name: callz

on:
  workflow_call:
    inputs:
      accountbundle:
        required: true
        type: string

jobs:
  setup:
    name: 'setup'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    permissions:
      contents: read
      id-token: write

    outputs:
      account_ids: ${{steps.unbundle_accounts.outputs.account_ids}}
    steps:
      - name: unbundle accounts
        id: unbundle_accounts
        run: |
          echo "account_ids="$(echo ${{ inputs.accountbundle }} | fold -w12 |  jq -R . | jq -s . ) >> "$GITHUB_OUTPUT"
  called:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        regions: ${{ vars.HOME_REGION }}
        accounts: ${{fromJson(needs.setup.outputs.account_ids)}}

    steps:
      - name: Print OS
        run: |
          echo ${{ matrix.region }}
          echo ${{ inputs.accountbundle }} | fold -w12
        shell: bash

