name: callz

on:
  workflow_call:
    inputs:
      accountbundle:
        required: true
        type: string

jobs:
  setup:
    name: 'setup'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    permissions:
      contents: read
      id-token: write

    outputs:
      account_ids: ${{steps.unbundle_accounts.outputs.account_ids}}
    steps:
      - name: unbundle accounts
        id: unbundle_accounts
        run: |
          echo "account_ids="$(echo ${{ inputs.accountbundle }} | fold -w12 |  jq -R . | jq -s . ) >> "$GITHUB_OUTPUT"
  called:
    name: 'fanout'
    uses: ./.github/workflows/access-analyzer.yml
    with:
      account_id: ${{matrix.account_id}}
      region: ${{matrix.region}}
      workflow: 'access-analyzer'
      workingdirectory: './regional/access-analyzer/'
    needs: setup
    permissions:
      contents: read
      id-token: write
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        region: 
          - ${{ vars.HOME_REGION }}
        account_id: ${{fromJson(needs.setup.outputs.account_ids)}}