name: reusable-fanout

on:
  workflow_call:
    inputs:
      accountbundle:
        required: true
        type: string
      additionalregions:
        required: true
        type: boolean
        default: false
  
jobs:
  setup:
    name: 'setup'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    permissions:
      contents: read
      id-token: write

    outputs:
      account_ids: ${{steps.unbundle_accounts.outputs.account_ids}}
      regions: ${{steps.unbundle_accounts.outputs.regions}}
    steps:
      - name: unbundle accounts
        id: unbundle_accounts
        run: |
          echo "account_ids="$(echo ${{ inputs.accountbundle }} | fold -w12 |  jq -R . | jq -s . ) >> "$GITHUB_OUTPUT"
          if [ ${{ inputs.additionalregions }}  ];
          then
            echo "regions="$(echo "${{ vars.HOME_REGION }} ${{ vars.ADDITIONAL_REGIONS }}" | jq -R . | jq -s . ) >> "$GITHUB_OUTPUT"
          else
            echo "regions="$(echo "${{ vars.HOME_REGION }}" | jq -R . | jq -s . ) >> "$GITHUB_OUTPUT"
          fi

  access-analyzer:
    name: 'access-analyzer'
    uses: ./.github/workflows/reusable-tf-deploy.yml
    with:
      account_id: ${{matrix.account_id}}
      region: ${{matrix.region}}
      workflow: 'access-analyzer'
      workingdirectory: './regional/access-analyzer/'
    needs: setup
    permissions:
      contents: read
      id-token: write
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        regions: ${{fromJson(needs.setup.outputs.regions)}}
        account_id: ${{fromJson(needs.setup.outputs.account_ids)}}